// packages/react-app/src/app/app.tsx
import { ReactLib } from '@nx-yarn-pnp-example/react-lib';
import { tsLib } from '@nx-yarn-pnp-example/ts-lib';
import NxWelcome from './nx-welcome';

export function App() {
  tsLib();

  return (
    <>
      <NxWelcome title="react-app" />
      <ReactLib />
      <div />
    </>
  );
}

export default App;

// packages/angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { tsLib } from '@nx-yarn-pnp-example/ts-lib';

@Component({
  selector: 'nx-yarn-pnp-example-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'angular-app';

  ngOnInit(): void {
    tsLib();
  }
}

<nx-yarn-pnp-example-nx-welcome></nx-yarn-pnp-example-nx-welcome>
<nx-yarn-pnp-example-hello-world></nx-yarn-pnp-example-hello-world>
